# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
        APP_SETTINGS: ${{ secrets.APP_SETTINGS }}
        TEST_CONFIG: ${{ secrets.TEST_CONFIG }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup appsettings.json
      run: echo "$APP_SETTINGS" > VisconSupportAPI/appsettings.json
      working-directory: ${{ github.workspace }}
    
    - name: Setup testconfig.json
      run: echo "$TEST_CONFIG" > VisconSupportAPI.Tests/testconfig.json
      working-directory: ${{ github.workspace }}
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
